### ISSUE TITLE
serial-native won't compile

### ISSUE THREAD

**Issue by Race666** [calimero-project/serial-native#2]
Since commit feed1be8f1300d915eaecd481235634718531d48 serial-native won't compile:

```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.github.calimero:serial-native:[unknown-version]: Could not find artifact com.github.calimero:calimero-parent:pom:2.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.github.calimero:serial-native:[unknown-version] (/root/calimero-build/serial-native/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.github.calimero:serial-native:[unknown-version]: Could not find artifact com.github.calimero:calimero-parent:pom:2.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 10 -> [Help 2]
```

**Comment by bmalinowsky** [comment]
I might be missing some details, but a quick check for both `clean` and `compile` targets resolve the parent just fine (using calimero-parent-2.4-20180509.195940-13.pom)

**Comment by bmalinowsky** [comment]
Ok, got it. If there is no snapshot proxy, needs same workaround as in the other repos ...

**Comment by bmalinowsky** [comment]
Done in d6ceae07afc5444ea32df3f6c7a39ee953cd1c6d.

**Comment by Race666** [comment]
Ok, compiling works! Thanks 

Am 16.05.2018 14:22, schrieb bmalinowsky: 

> Done in d6ceae0 [1]. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1]
https://github.com/calimero-project/serial-native/commit/d6ceae07afc5444ea32df3f6c7a39ee953cd1c6d
[2]
https://github.com/calimero-project/serial-native/issues/2#issuecomment-389499064
[3]
